from character import Character,Enemy, Companion
sword = object

liam = Character("Liam", "A brave philosopher king")
liam.SetConvo("Hi, Have you heard of Nietzsche?")
liam.Describe()
liam.Talk()
liam.Fight(sword)
print("")
lauren = Character("Lauren", "A beautiful and unexotic nymph")
lauren.SetConvo("Hey there, Would you like to 'come' inside? **Winks**")
lauren.Describe()
lauren.Talk()
lauren.Fight(sword)
print("")
jacque = Enemy("Jacques", "A ragamuffin without a cause")
jacque.Describe()
jacque.Talk()
jacque.Fight(sword)
jacque.SetWeakness("peanuts")
jacque.Fight("peanuts")
fightWithWhat = input("What will you fight with?>>> ")
jacque.Fight(fightWithWhat)
print("")
charlie = Companion("Charlie", "Liam's Sidekick")
charlie.SetAnimalType("Dog")
charlie.Describe()